// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-business-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_business_info_default = defineTool({
  name: "get_business_info",
  title: "Get business info",
  description: "Return Arman IT contact details, service area, phone, WhatsApp, email, and website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Arman IT Solutions",
      tagline: "On-site IT Support \u2013 we come to you",
      serviceArea: "Perth, WA and all surrounding suburbs",
      phone: "0424 558 244",
      whatsapp: "https://wa.me/61424558244",
      email: "arman@armanitsolutions.com",
      website: "https://www.armanitsolutions.com",
      facebook: "https://facebook.com/armanitsolutions",
      guarantee: "No fix, no fee"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "Return the full list of home and small business IT services Arman IT offers in Perth.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const services = {
      home: [
        "Computer troubleshooting (Windows & macOS)",
        "Printer and scanner setup",
        "WiFi and internet issues",
        "Mesh WiFi setup",
        "Email setup/recovery (Gmail, Outlook, Apple ID)",
        "Phone setup (iPhone & Android)",
        "Virus removal",
        "Smart TV setup"
      ],
      smallBusiness: [
        "Office network and WiFi setup",
        "Printer and scanner deployment",
        "Email configuration and recovery",
        "New workstation setup",
        "On-site troubleshooting and support"
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
      structuredContent: services
    };
  }
});

// src/lib/mcp/tools/submit-quote-request.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var submit_quote_request_default = defineTool3({
  name: "submit_quote_request",
  title: "Submit quote request",
  description: "Submit a quote request to Arman IT. Sends the same email as the website contact form. Use only with the customer's explicit consent.",
  inputSchema: {
    name: z.string().trim().min(1).describe("Customer full name."),
    email: z.string().trim().email().describe("Customer email address."),
    phone: z.string().trim().min(1).describe("Customer mobile number."),
    address: z.string().trim().min(1).describe("Service address in Perth."),
    description: z.string().trim().min(1).describe("Description of the IT issue or service needed.")
  },
  annotations: { readOnlyHint: false, openWorldHint: true },
  handler: async (input) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!supabaseUrl || !anonKey) {
      return {
        content: [{ type: "text", text: "Server is not configured to send emails." }],
        isError: true
      };
    }
    const res = await fetch(`${supabaseUrl}/functions/v1/send-transactional-email`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: anonKey,
        Authorization: `Bearer ${anonKey}`
      },
      body: JSON.stringify({
        template: "quote-request",
        data: input
      })
    });
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      return {
        content: [
          { type: "text", text: `Failed to submit quote request (${res.status}): ${text}` }
        ],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Quote request submitted for ${input.name}. Arman IT will be in touch shortly.`
        }
      ],
      structuredContent: { ok: true }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "arman-it-mcp",
  title: "Arman IT",
  version: "0.1.0",
  instructions: "Tools for Arman IT Solutions, a mobile IT support business in Perth, WA. Use `get_business_info` for contact details, `list_services` for what Arman IT offers, and `submit_quote_request` to send a quote request on behalf of a customer (with their explicit consent).",
  tools: [get_business_info_default, list_services_default, submit_quote_request_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
